spring.application.name=spring-security
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/security
spring.datasource.username=elhassen
spring.datasource.password=32204361
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update